---
# =============================================
# Valeurs par défaut pour la création de VMs clonées
# =============================================
pmx_api_token_secret: "{{ proxmox_api_token_secret }}"
pmx_api_token_id: "{{ proxmox_api_token_id }}"
pmx_node: "{{ proxmox_node | default('pve') }}"
pmx_storage: "{{ proxmox_storage | default('local') }}"
pmx_api_host: "{{ proxmox_api_host }}"
pmx_api_user: "{{ proxmox_api_user }}"
ssh_pub_key_path: "~/.ssh/id_rsa.pub"
