---
# =============================================
# Valeurs par défaut pour la création de VMs clonées
# =============================================

# Stockage par défaut pour les clones et cloud-init
proxmox_vm_defaults:
  storage: "local"
  ssh_pub_key_path: "~/.ssh/id_rsa_wbx.pub"
  ci_user: "admin"
  ci_password: "ChangeMe123!"

# Liste des VMs à provisionner (peut être surchargée par inventories/all.yml)
proxmox_vms:
  - name: "opnsense"
    vmid: 106
    template: "opnsense-template"
    memory: 2048
    cores: 2
    disk_size: "8G"
    net0: "virtio,bridge=vmbr0"
    net1: "virtio,bridge=vmbr1"
    ipconfig0: "ip=dhcp"
    ipconfig1: "ip=192.168.1.2/24"
    tags: ["firewall"]

  - name: "bastion"
    vmid: 102
    template: "debian-cloud-template"
    memory: 1024
    cores: 1
    disk_size: "10G"
    net0: "virtio,bridge=vmbr1"          # LAN interne
    net1: "virtio,bridge=vmbr0"          # WAN/Internet
    ipconfig0: "ip=192.168.1.10/24,gw=192.168.1.1"
    ipconfig1: "ip=dhcp"
    tags: ["bastion"]

  - name: "haproxy"
    vmid: 103
    template: "debian-cloud-template"
    memory: 1024
    cores: 1
    disk_size: "10G"
    net0: "virtio,bridge=vmbr1"
    ipconfig0: "ip=192.168.1.20/24,gw=192.168.1.1"
    tags: ["haproxy"]

  - name: "docker-manager"
    vmid: 104
    template: "debian-cloud-template"
    memory: 2048
    cores: 2
    disk_size: "20G"
    net0: "virtio,bridge=vmbr1"
    ipconfig0: "ip=192.168.1.30/24,gw=192.168.1.1"
    tags: ["docker"]
