---
- name: Installer Docker et plugins
  apt:
    name:
      - docker.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Créer le dossier /opt/services
  file:
    path: /opt/services
    state: directory

- name: Générer docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/services/docker-compose.yml

- name: Démarrer les services Docker (compose v2)
  community.docker.docker_compose_v2:
    project_src: /opt/services
    state: present
