# Playbook maître orchestrant tous les rôles                         # commentaire: point d'entrée
- hosts: proxmox                                                     # commentaire: cible le groupe 'proxmox' de l'inventaire
  become: true                                                       # commentaire: exécute en privilèges root
  roles:                                                             # commentaire: liste des rôles à dérouler
    - proxmox-host                                                   # commentaire: configure bridges + NAT + règles persistantes
    - opnsense-vm                                                    # commentaire: crée la VM OPNsense (2 NIC)
    - services-vm                                                    # commentaire: crée la VM services (Docker/HAProxy/Traefik/Portainer ultérieurement)
