---
# Tâches pour configurer le Proxmox Host

- name: Configurer les bridges réseau
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  notify: Restart networking

- name: Activer le forwarding IP
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
