---
- name: Gather current network configuration
  ansible.builtin.setup:
    gather_subset:
      - network

- name: Deploy Proxmox network configuration (bridges)
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  notify: Restart networking
  tags: [network]

- name: Ensure vmbr2 is enabled if configured
  ansible.builtin.command: ifup vmbr2
  when: enable_vmbr2 and ('vmbr2' not in ansible_facts.interfaces)
  tags: [network]
