---
# ==============================================
# SSH root key
# ==============================================
- name: Assurer la présence de la clé SSH root
  ansible.builtin.authorized_key:
    user: root
    key: "{{ ssh_public_key }}"
    state: present

# ==============================================
# Vérification version Proxmox
# ==============================================
- name: Vérifier version Proxmox
  ansible.builtin.command: pveversion
  register: pve_version
  changed_when: false

- name: Afficher version Proxmox
  debug:
    var: pve_version.stdout

# ==============================================
# Déploiement configuration réseau
# ==============================================
- name: Déployer les interfeces réseau
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  notify: Restart networking


# ==============================================
# Dépôts et mise à jour
# ==============================================
- name: Supprimer le dépôt enterprise
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Ajouter dépôt pve-no-subscription
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: '^deb http://download.proxmox.com/debian/pve'
    line: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
    state: present

- name: Mettre à jour cache APT
  ansible.builtin.apt:
    update_cache: yes

- name: Installer outils requis
  ansible.builtin.apt:
    name:
      - qemu-guest-agent
      - cloud-init
      - ifupdown2
      - htop
      - vim
      - bzip2
      - pv
      - bridge-utils
      - gzip
      - wget
      - curl
      - gnupg
      - unzip
      - expect 
      - socat 
    state: present
    update_cache: yes

