---
- name: Assurer la présence de la clé SSH du bastion
  ansible.builtin.authorized_key:
    user: "{{ bastion_user }}"
    key: "{{ bastion_ssh_pub_key }}"
    state: present

- name: Installer utilitaires de base (fail2ban, ufw, htop)
  ansible.builtin.apt:
    name:
      - fail2ban
      - ufw
      - htop
    state: present
    update_cache: yes

- name: Configurer UFW par défaut
  ansible.builtin.ufw:
    state: enabled
    policy: "{{ bastion_ufw_default_incoming }}/{{ bastion_ufw_default_outgoing }}"

- name: Autoriser ports spécifiques dans UFW
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ bastion_firewall_allowed_ports }}"

- name: Vérifier connectivité LAN et Internet
  ansible.builtin.ping:
    data: "ping test"
