---
- name: Install security packages
  ansible.builtin.apt:
    name:
      - fail2ban
      - ufw
    state: present
    update_cache: true
  tags: [bastion]

- name: Enable UFW and allow SSH
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp
  tags: [bastion]

- name: Enable UFW
  community.general.ufw:
    state: enabled
  tags: [bastion]

- name: Deploy SSH hardening config
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: Restart SSH
  tags: [bastion]

- name: Ensure root SSH key is installed
  ansible.builtin.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags: [bastion]
