# ==========================
# Proxmox API / Node
# ==========================
# vars/main.yml
proxmox_host: "{{ proxmox_api_host }}"
proxmox_user: "{{ proxmox_api_user }}"
pmx_api_token_secret: "{{ proxmox_api_token_secret }}"
pmx_api_token_id: "{{ proxmox_api_token_id }}"
pmx_node: "{{ proxmox_node | default('pve') }}"
pmx_storage: "{{ proxmox_storage | default('local') }}"

ssh_pub_key_path: "~/.ssh/id_rsa.pub"

