# roles/opnsense-vm/tasks/main.yml

- name: Vérifier connectivité SSH vers OPNsense
  ping:

- name: Déployer fichier règles firewall/NAT
  template:
    src: rules.v4.j2
    dest: /tmp/rules.v4

- name: Appliquer les règles NAT et firewall via SSH
  shell: |
    sudo pfctl -f /tmp/rules.v4
    sudo pfctl -e
  args:
    warn: false

- name: Vérifier NAT vers Internet
  shell: ping -c 3 8.8.8.8
  register: ping_result
  ignore_errors: yes

- name: Afficher résultat test NAT
  debug:
    msg: "Ping Internet via OPNsense: {{ ping_result.stdout }}"
