---
# Tâches pour configurer OPNsense
# Note: À adapter selon votre version OPNsense

- name: Recharger les règles NAT
  ansible.builtin.command: >
    /usr/local/sbin/configctl nat reload

- name: Appliquer la politique firewall par défaut
  ansible.builtin.command: >
    /usr/local/sbin/configctl filter reload
