# Variables globales utilisées par tous les rôles

# Bridges Proxmox
proxmox_bridge_wan: "vmbr0"
proxmox_bridge_lan: "vmbr1"

# Réseau LAN interne
lan_network: "192.168.100.0/24"
lan_gateway: "192.168.100.1"

# IP unique OVH
ovh_ip: "VOTRE_IP_OVH"
ovh_netmask: "255.255.255.0"
ovh_gateway: "IP_GATEWAY_OVH"

# Utilisateur Ansible
ansible_user: "root"
