# group_vars/all.yml
# Variables globales

---
public_ip: "X.X.X.X"              # Remplacer par votre IP OVH publique
lan_network: "192.168.100.0/24"
gateway_lan: "192.168.100.1"      # IP LAN de l'OPNsense
ssh_user: "root"                  # Utilisateur SSH
ssh_private_key: "~/.ssh/id_ed25519"
proxmox_api_url: "https://proxmox.example.com:8006/api2/json"
proxmox_user: "root@pam"
proxmox_password: "CHANGE_ME"
