version: '3.9'
services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible
    volumes:
      - ../ansible:/ansible:rw
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /ansible
    tty: true
