version: "3.9"

services:
  ansible:
    build: .
    container_name: ansible-ovh
    volumes:
      - ../ansible:/ansible         # Monte le projet Ansible
      - ~/.ssh:/root/.ssh:ro        # Monte les clés SSH pour Proxmox/GitHub
    working_dir: /ansible
    tty: true                       # Pour pouvoir rester en mode interactif
    environment:
      ANSIBLE_HOST_KEY_CHECKING: "False" # Désactive la vérification des clés SSH
