# roles/services-vm/tasks/haproxy.yml

- name: Installer HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Déployer la configuration HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Activer et démarrer HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes
