# roles/services-vm/tasks/main.yml
# Déploiement Docker + Traefik + Portainer
# On suppose Debian/Ubuntu avec Docker préinstallé

- name: Installer Docker
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: Copier docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/docker-compose.yml

- name: Lancer services
  shell: "docker-compose -f /home/{{ ansible_user }}/docker-compose.yml up -d"
  args:
    chdir: "/home/{{ ansible_user }}"
