---
# Tâches pour configurer la VM Services avec Docker, Traefik et HAProxy

- name: Copier docker-compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/docker-compose.yml
    owner: {{ ansible_user }}
    group: {{ ansible_user }}
    mode: '0644'

- name: Copier configuration HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Démarrer HAProxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: yes

- name: Lancer Docker Compose
  community.docker.docker_compose:
    project_src: /home/{{ ansible_user }}/
    state: present
