# roles/services-vm/tasks/main.yml

- name: Installer Docker et docker-compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: Créer répertoire docker
  file:
    path: /opt/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Déployer docker-compose.yml via template
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker/docker-compose.yml

- name: Lancer les services Docker (Traefik + Portainer)
  shell: docker-compose up -d
  args:
    chdir: /opt/docker

- include_tasks: haproxy.yml
  when: inventory_hostname == "haproxy"
