# roles/haproxy-vm/tasks/main.yml
# Déploiement et configuration HAProxy sur la VM HAProxy

- name: Installer HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Activer HAProxy au démarrage
  systemd:
    name: haproxy
    enabled: yes
    state: started

- name: Copier la configuration HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: Reload HAProxy
