---
# Playbook principal qui orchestre tous les rôles

- name: Provisionner le Proxmox Host
  hosts: proxmox
  become: yes
  roles:
    - proxmox-host

- name: Déployer OPNsense VM
  hosts: opnsense
  become: yes
  roles:
    - opnsense-vm

- name: Déployer Services VM
  hosts: services
  become: yes
  roles:
    - services-vm
