- hosts: proxmox
  roles:
    - { role: proxmox-host, tags: ["network"] }

- hosts: bastion_group
  roles:
    - { role: bastion, tags: ["bastion"] }

- hosts: opnsense_group
  roles:
    - { role: opnsense, tags: ["opnsense"] }
    - vpn-client

- hosts: haproxy_group
  roles:
    - { role: haproxy, tags: ["haproxy"] }

- hosts: services_group
  roles:
    - { role: services, tags: ["services"] }
